baseURL = 'http://gemignani.github.io'
languageCode = 'en-gb'
title = "Doug Blog"
theme = 'ananke'

[sitemap]                 # essential                     
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu             
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"


[params]
                    
  author = "Douglas Lima"
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2014"            # Site creation time        

  # site info (optional)
  logoTitle = "Doug Findings"        # default: the title value    
  keywords = ["Doug", "homeassistant" ,"automation", "electronics"]
  description = "Doug stuff here"


